name: Build Reactjs and Deploy on Pages
on:
  push:
    branches: [main]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Deploy sample pages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - id: Build-Reactjs
        uses: botamochi6277/reactjs-ble-console@main
      - name: git setting
        run: |
          git config --local user.email "action_runner@users.noreply.github.com"
          git config --local user.name "action runner"
      - name: Commit and push files
        run: |
          git checkout -b gh-pages
          git add .
          git commit -m "build pages" -a
          git push origin HEAD:gh-pages --force
