name: A job to build and deploy page
on:
  push:
    branches: [main]

jobs:
  paging_jobs:
    runs-on: ubuntu-latest
    name: A job to draw lbr design
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: build pages
        run: |
          npm install
          npm run build
      - name: git setting
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
        run: |
          git config --local user.email "action_runner@users.noreply.github.com"
          git config --local user.name "action runner"
      - name: remove ignore to push build
        run: rm .gitignore
      - name: Commit and push files
        run: |
          git checkout -b gh-pages
          git add .
          git commit -m "build pages" -a
          git push origin HEAD:gh-pages --force
